version: 2

updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
      timezone: Asia/Jakarta

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: Asia/Jakarta
    labels:
      - dependencies
    groups:
      artifacts:
        patterns: [actions/*-artifact, actions/deploy-pages]
      runtimes:
        patterns: [oven-sh/setup-bun, shivammathur/setup-php]

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      timezone: Asia/Jakarta
    versioning-strategy: increase-if-necessary
    groups:
      dependencies:
        dependency-type: production
        patterns: ['*']
      dev-dependencies:
        dependency-type: development
        patterns: ['*']

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      timezone: Asia/Jakarta
    versioning-strategy: increase-if-necessary
    groups:
      commitlint:
        patterns: ['@commitlint/*']
